set(_CATKIN_CURRENT_PACKAGE "rc_msgs")
set(rc_msgs_VERSION "0.0.0")
set(rc_msgs_MAINTAINER "myx <myx@todo.todo>")
set(rc_msgs_PACKAGE_FORMAT "2")
set(rc_msgs_BUILD_DEPENDS "message_generation" "std_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(rc_msgs_BUILD_EXPORT_DEPENDS "message_generation" "std_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(rc_msgs_BUILDTOOL_DEPENDS "catkin")
set(rc_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(rc_msgs_EXEC_DEPENDS "message_runtime" "message_generation" "std_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(rc_msgs_RUN_DEPENDS "message_runtime" "message_generation" "std_msgs" "geometry_msgs" "actionlib" "actionlib_msgs")
set(rc_msgs_TEST_DEPENDS )
set(rc_msgs_DOC_DEPENDS )
set(rc_msgs_URL_WEBSITE "")
set(rc_msgs_URL_BUGTRACKER "")
set(rc_msgs_URL_REPOSITORY "")
set(rc_msgs_DEPRECATED "")