set(_CATKIN_CURRENT_PACKAGE "map")
set(map_VERSION "1.0.0")
set(map_MAINTAINER " <TODO@email.com>")
set(map_PACKAGE_FORMAT "2")
set(map_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(map_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(map_BUILDTOOL_DEPENDS "catkin")
set(map_BUILDTOOL_EXPORT_DEPENDS )
set(map_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(map_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(map_TEST_DEPENDS )
set(map_DOC_DEPENDS )
set(map_URL_WEBSITE "")
set(map_URL_BUGTRACKER "")
set(map_URL_REPOSITORY "")
set(map_DEPRECATED "")