set(_CATKIN_CURRENT_PACKAGE "rc_description")
set(rc_description_VERSION "0.0.0")
set(rc_description_MAINTAINER "myx <myx@todo.todo>")
set(rc_description_PACKAGE_FORMAT "2")
set(rc_description_BUILD_DEPENDS )
set(rc_description_BUILD_EXPORT_DEPENDS )
set(rc_description_BUILDTOOL_DEPENDS "catkin")
set(rc_description_BUILDTOOL_EXPORT_DEPENDS )
set(rc_description_EXEC_DEPENDS "xacro")
set(rc_description_RUN_DEPENDS "xacro")
set(rc_description_TEST_DEPENDS )
set(rc_description_DOC_DEPENDS )
set(rc_description_URL_WEBSITE "")
set(rc_description_URL_BUGTRACKER "")
set(rc_description_URL_REPOSITORY "")
set(rc_description_DEPRECATED "")