set(_CATKIN_CURRENT_PACKAGE "rc_config")
set(rc_config_VERSION "0.0.0")
set(rc_config_MAINTAINER "myx <myx@todo.todo>")
set(rc_config_PACKAGE_FORMAT "2")
set(rc_config_BUILD_DEPENDS )
set(rc_config_BUILD_EXPORT_DEPENDS )
set(rc_config_BUILDTOOL_DEPENDS "catkin")
set(rc_config_BUILDTOOL_EXPORT_DEPENDS )
set(rc_config_EXEC_DEPENDS )
set(rc_config_RUN_DEPENDS )
set(rc_config_TEST_DEPENDS )
set(rc_config_DOC_DEPENDS )
set(rc_config_URL_WEBSITE "")
set(rc_config_URL_BUGTRACKER "")
set(rc_config_URL_REPOSITORY "")
set(rc_config_DEPRECATED "")