set(_CATKIN_CURRENT_PACKAGE "robot_state_controller")
set(robot_state_controller_VERSION "0.1.8")
set(robot_state_controller_MAINTAINER "Qiayuan Liao <liaoqiayuan@gmail.com>")
set(robot_state_controller_PACKAGE_FORMAT "2")
set(robot_state_controller_BUILD_DEPENDS "roscpp" "rc_common" "controller_interface" "kdl_parser" "tf2_kdl" "realtime_tools")
set(robot_state_controller_BUILD_EXPORT_DEPENDS "roscpp" "rc_common" "controller_interface" "kdl_parser" "tf2_kdl" "realtime_tools")
set(robot_state_controller_BUILDTOOL_DEPENDS "catkin")
set(robot_state_controller_BUILDTOOL_EXPORT_DEPENDS )
set(robot_state_controller_EXEC_DEPENDS "roscpp" "rc_common" "controller_interface" "kdl_parser" "tf2_kdl" "realtime_tools")
set(robot_state_controller_RUN_DEPENDS "roscpp" "rc_common" "controller_interface" "kdl_parser" "tf2_kdl" "realtime_tools")
set(robot_state_controller_TEST_DEPENDS )
set(robot_state_controller_DOC_DEPENDS )
set(robot_state_controller_URL_WEBSITE "")
set(robot_state_controller_URL_BUGTRACKER "")
set(robot_state_controller_URL_REPOSITORY "")
set(robot_state_controller_DEPRECATED "")