// Generated by gencpp from file rc_msgs/ActionCmd.msg
// DO NOT EDIT!


#ifndef RC_MSGS_MESSAGE_ACTIONCMD_H
#define RC_MSGS_MESSAGE_ACTIONCMD_H

#include <ros/service_traits.h>


#include <rc_msgs/ActionCmdRequest.h>
#include <rc_msgs/ActionCmdResponse.h>


namespace rc_msgs
{

struct ActionCmd
{

typedef ActionCmdRequest Request;
typedef ActionCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionCmd
} // namespace rc_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rc_msgs::ActionCmd > {
  static const char* value()
  {
    return "903779543030b66caa508cdbd86af033";
  }

  static const char* value(const ::rc_msgs::ActionCmd&) { return value(); }
};

template<>
struct DataType< ::rc_msgs::ActionCmd > {
  static const char* value()
  {
    return "rc_msgs/ActionCmd";
  }

  static const char* value(const ::rc_msgs::ActionCmd&) { return value(); }
};


// service_traits::MD5Sum< ::rc_msgs::ActionCmdRequest> should match
// service_traits::MD5Sum< ::rc_msgs::ActionCmd >
template<>
struct MD5Sum< ::rc_msgs::ActionCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rc_msgs::ActionCmd >::value();
  }
  static const char* value(const ::rc_msgs::ActionCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rc_msgs::ActionCmdRequest> should match
// service_traits::DataType< ::rc_msgs::ActionCmd >
template<>
struct DataType< ::rc_msgs::ActionCmdRequest>
{
  static const char* value()
  {
    return DataType< ::rc_msgs::ActionCmd >::value();
  }
  static const char* value(const ::rc_msgs::ActionCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rc_msgs::ActionCmdResponse> should match
// service_traits::MD5Sum< ::rc_msgs::ActionCmd >
template<>
struct MD5Sum< ::rc_msgs::ActionCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rc_msgs::ActionCmd >::value();
  }
  static const char* value(const ::rc_msgs::ActionCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rc_msgs::ActionCmdResponse> should match
// service_traits::DataType< ::rc_msgs::ActionCmd >
template<>
struct DataType< ::rc_msgs::ActionCmdResponse>
{
  static const char* value()
  {
    return DataType< ::rc_msgs::ActionCmd >::value();
  }
  static const char* value(const ::rc_msgs::ActionCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RC_MSGS_MESSAGE_ACTIONCMD_H
